POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "ad@a.se",
    "password": "1234"
}

###
POST http://localhost:5000/api/auth/logout
Content-Type: application/json