GET http://localhost:5000/api/playerResult/60014e08742f450017f11968
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmI1YzIyMjc4M2Y0MDAxNzUwYzJlNSIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmZiNWM5OTI3ODNmNDAwMTc1MGMyZTYiLCI1ZmZiNWQ0ZDI3ODNmNDAwMTc1MGMyZTgiXSwiYWN0aXZlVGVhbSI6IjVmZmI1Yzk5Mjc4M2Y0MDAxNzUwYzJlNiIsImlhdCI6MTYxMDQ0Mzc3MX0.ySr56jcWPyZetB1_FgfmfNAyrtLu8AowGagF9bfR9VU

###
GET http://localhost:5000/api/playerResult/team/60009b2acca23a0017052124
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMDA5MGI0Y2NhMjNhMDAxNzA1MjEyMyIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI2MDAwOWIyYWNjYTIzYTAwMTcwNTIxMjQiXSwiYWN0aXZlVGVhbSI6IjYwMDA5YjJhY2NhMjNhMDAxNzA1MjEyNCIsImlhdCI6MTYxMDk2NjgxN30.DuvxeTiO1dzZoiij0L8ANm0UvALZLiDz_h4cTAtZgW8

###

POST http://localhost:5000/api/playerResult
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmI1YzIyMjc4M2Y0MDAxNzUwYzJlNSIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmZiNWM5OTI3ODNmNDAwMTc1MGMyZTYiLCI1ZmZiNWQ0ZDI3ODNmNDAwMTc1MGMyZTgiXSwiYWN0aXZlVGVhbSI6IjVmZmI1Yzk5Mjc4M2Y0MDAxNzUwYzJlNiIsImlhdCI6MTYxMDQ0Mzc3MX0.ySr56jcWPyZetB1_FgfmfNAyrtLu8AowGagF9bfR9VU

{
    "gameId": "600162efb7043000174e0d90",
    "userId": "6001637bb7043000174e0d91",
    "goals": 10,
    "assists": 10,
    "penalties": 10
}

###

DELETE http://localhost:5000/api/playerResult/6005538aea2d1300178f5f85/60055381ea2d1300178f5f84
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmI1YzIyMjc4M2Y0MDAxNzUwYzJlNSIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmZiNWM5OTI3ODNmNDAwMTc1MGMyZTYiLCI1ZmZiNWQ0ZDI3ODNmNDAwMTc1MGMyZTgiXSwiYWN0aXZlVGVhbSI6IjVmZmI1Yzk5Mjc4M2Y0MDAxNzUwYzJlNiIsImlhdCI6MTYxMDQ0Mzc3MX0.ySr56jcWPyZetB1_FgfmfNAyrtLu8AowGagF9bfR9VU

###