POST http://localhost:5000/api/playerResult
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZmI1YzIyMjc4M2Y0MDAxNzUwYzJlNSIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmZiNWM5OTI3ODNmNDAwMTc1MGMyZTYiLCI1ZmZiNWQ0ZDI3ODNmNDAwMTc1MGMyZTgiXSwiYWN0aXZlVGVhbSI6IjVmZmI1Yzk5Mjc4M2Y0MDAxNzUwYzJlNiIsImlhdCI6MTYxMDQ0Mzc3MX0.ySr56jcWPyZetB1_FgfmfNAyrtLu8AowGagF9bfR9VU

{
    "gameId": "60009b75cca23a0017052125",
    "userId": "600090b4cca23a0017052123",
    "goals": 2,
    "assists": 2,
    "penalties": 2
}