POST http://localhost:5000/api/requests/5ff1f29c98be2200175b7515
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjFmMzQ1OThiZTIyMDAxNzViNzUxNiIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmYxZjM2Mzk4YmUyMjAwMTc1Yjc1MTciXSwiYWN0aXZlVGVhbSI6IjVmZjFmMzYzOThiZTIyMDAxNzViNzUxNyIsImlhdCI6MTYwOTg1NzA4OH0.-M7xFv3I2EG6d97J8GNbDr0Rxq0aU8GSikKw5T0oeMY

{
    "player": "5ff1f34598be2200175b7516",
    "message": "Hej, får jag gå med i ditt tuffa lag? SNÄLLA!!!!"
}

###

DELETE http://localhost:5000/api/requests/deleteRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjJlMzc0MDM5MWE2MDAxNzQ0YzQyMSIsImZpcnN0bmFtZSI6IkxlaWYiLCJsYXN0bmFtZSI6Ik9sc3NvbiIsImVtYWlsIjoibG9rZXRAYmluZ28uY29tIiwidGVhbSI6WyI1ZmYyZTQwNDAzOTFhNjAwMTc0NGM0MjIiLCI1ZmYyZTQyNTAzOTFhNjAwMTc0NGM0MjMiXSwiYWN0aXZlVGVhbSI6IjVmZjJlNDI1MDM5MWE2MDAxNzQ0YzQyMyIsImlhdCI6MTYwOTc3NzAzNX0.sf4TMxyDkmoA9WXcGnghZFgsssw0YVrsG7jpLx8llZg

{
    "requestId": "5ff2fcb02f36f30017de7e25"
}

###
