POST http://localhost:5000/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZWFmZGUwYjVkYzg0MWMzNDYwMDdlMSIsImZpcnN0bmFtZSI6ImFkIiwibGFzdG5hbWUiOiJhZCIsImVtYWlsIjoiYWRAYS5zZSIsInRlYW0iOltdLCJpYXQiOjE2MDkyMzYwMjB9.UxMbEiBb1Pmk3HzoMMGBXjNSEHIMd2cTTcVAf6rj8P0

{
    "name": "Hasses Sega Gubbar",
    "city": "Göteborg",
    "sport": "Innebandy"
}

###
GET http://localhost:5000/api/teams/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTk5ZGY3YjBjZmJmMWY4OGMxOWZjOCIsImZpcnN0bmFtZSI6ImhhdmUiLCJsYXN0bmFtZSI6InRlYW0iLCJlbWFpbCI6ImhhdmVAdGVhbS5zZSIsInRlYW0iOltdLCJpYXQiOjE2MDkxNDU4Nzh9.AH1_bNslI5NvD18tSAYIL_oQq24MktxEfLIv2OrULfE