POST http://localhost:5000/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTM0ZjU0NGZkNGMzMGY1ODBkMmMzZiIsImZpcnN0bmFtZSI6ImEiLCJsYXN0bmFtZSI6ImEiLCJlbWFpbCI6ImFAYS5zZSIsInRlYW0iOltdLCJpYXQiOjE2MDg3MzI1MzN9.4xyR9kCknImEyVh6L6EVwKrrusmdJneFxZ_XGeh2-7I

{
    "name": "HSG",
    "city": "Göteborg",
    "sport": "Innebandy"
}