POST http://localhost:5000/api/teams
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjFmMzQ1OThiZTIyMDAxNzViNzUxNiIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmYxZjM2Mzk4YmUyMjAwMTc1Yjc1MTciXSwiYWN0aXZlVGVhbSI6IjVmZjFmMzYzOThiZTIyMDAxNzViNzUxNyIsImlhdCI6MTYwOTc3MzYxMH0.xELgTR8vLRDLgNzNIqLqM3Spi3uhbbZ7AT60mfiQ1D0
{
    "name": "Hasses Sega Gubbar",
    "city": "Göteborg",
    "sport": "Innebandy"
}

###

GET http://localhost:5000/api/teams/findOne/5ff2fc652f36f30017de7e23
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjJlMzc0MDM5MWE2MDAxNzQ0YzQyMSIsImZpcnN0bmFtZSI6IkxlaWYiLCJsYXN0bmFtZSI6Ik9sc3NvbiIsImVtYWlsIjoibG9rZXRAYmluZ28uY29tIiwidGVhbSI6WyI1ZmYyZTQwNDAzOTFhNjAwMTc0NGM0MjIiLCI1ZmYyZTQyNTAzOTFhNjAwMTc0NGM0MjMiXSwiYWN0aXZlVGVhbSI6IjVmZjJlNDI1MDM5MWE2MDAxNzQ0YzQyMyIsImlhdCI6MTYwOTc2NTg3N30.E3USTZZmD00vujLQVP3n8L2zHBQlSOOsOV1lQu4fAgk

###

DELETE http://localhost:5000/api/teams/deletePlayer
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZWFmZGUwYjVkYzg0MWMzNDYwMDdlMSIsImZpcnN0bmFtZSI6ImFkIiwibGFzdG5hbWUiOiJhZCIsImVtYWlsIjoiYWRAYS5zZSIsInRlYW0iOlsiNWZlYWZlNWE2ZTQzMzkzYmFjYmIxOWE1Il0sImFjdGl2ZVRlYW0iOnsiZ2FtZXMiOltdLCJwbGF5ZXJzIjpbXSwibGVhZGVycyI6W3sidGVhbSI6WyI1ZmVhZmU1YTZlNDMzOTNiYWNiYjE5YTUiXSwiX2lkIjoiNWZlYWZkZTBiNWRjODQxYzM0NjAwN2UxIiwiZmlyc3RuYW1lIjoiYWQiLCJsYXN0bmFtZSI6ImFkIiwiZW1haWwiOiJhZEBhLnNlIiwicGFzc3dvcmQiOiIkMmIkMTAkU2xSSG4wM2wvaDlaQ1RSbnJOVlp4dW5Hc1FETmVSanNmSVRoUkRwZ2QzUXhUcHV6d1puNUMiLCJfX3YiOjEsImFjdGl2ZVRlYW0iOiI1ZmVhZmU1YTZlNDMzOTNiYWNiYjE5YTUifV0sInJlcXVlc3RzIjpbXSwiX2lkIjoiNWZlYWZlNWE2ZTQzMzkzYmFjYmIxOWE1IiwibmFtZSI6Ikhhc3NlcyBTZWdhIEd1YmJhciIsImNpdHkiOiJHw7Z0ZWJvcmciLCJzcG9ydCI6IklubmViYW5keSIsIl9fdiI6MH0sImlhdCI6MTYwOTI1Mzg4Mn0.WimR39MLODJil09_drnLxOV_O0LuGiRXIwjEnhh7dXI

{
    "teamId": "5feaf6705f8c970017f88a74",
    "userId": "5feaf5d75f8c970017f88a72"
}

###

DELETE http://localhost:5000/api/teams/deleteLeader
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZWFmZGUwYjVkYzg0MWMzNDYwMDdlMSIsImZpcnN0bmFtZSI6ImFkIiwibGFzdG5hbWUiOiJhZCIsImVtYWlsIjoiYWRAYS5zZSIsInRlYW0iOlsiNWZlYWZlNWE2ZTQzMzkzYmFjYmIxOWE1Il0sImFjdGl2ZVRlYW0iOnsiZ2FtZXMiOltdLCJwbGF5ZXJzIjpbXSwibGVhZGVycyI6W3sidGVhbSI6WyI1ZmVhZmU1YTZlNDMzOTNiYWNiYjE5YTUiXSwiX2lkIjoiNWZlYWZkZTBiNWRjODQxYzM0NjAwN2UxIiwiZmlyc3RuYW1lIjoiYWQiLCJsYXN0bmFtZSI6ImFkIiwiZW1haWwiOiJhZEBhLnNlIiwicGFzc3dvcmQiOiIkMmIkMTAkU2xSSG4wM2wvaDlaQ1RSbnJOVlp4dW5Hc1FETmVSanNmSVRoUkRwZ2QzUXhUcHV6d1puNUMiLCJfX3YiOjEsImFjdGl2ZVRlYW0iOiI1ZmVhZmU1YTZlNDMzOTNiYWNiYjE5YTUifV0sInJlcXVlc3RzIjpbXSwiX2lkIjoiNWZlYWZlNWE2ZTQzMzkzYmFjYmIxOWE1IiwibmFtZSI6Ikhhc3NlcyBTZWdhIEd1YmJhciIsImNpdHkiOiJHw7Z0ZWJvcmciLCJzcG9ydCI6IklubmViYW5keSIsIl9fdiI6MH0sImlhdCI6MTYwOTI1Mzg4Mn0.WimR39MLODJil09_drnLxOV_O0LuGiRXIwjEnhh7dXI

{
    "teamId": "5feaf6705f8c970017f88a74",
    "userId": "5feaf5d75f8c970017f88a72"
}

###

POST http://localhost:5000/api/teams/acceptRequest
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjJlZjVlMmYzNmYzMDAxN2RlN2UxZiIsImZpcnN0bmFtZSI6InRlc3QiLCJsYXN0bmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAY29tLmNvbSIsInRlYW0iOlsiNWZmMmU0MDQwMzkxYTYwMDE3NDRjNDIyIl0sImlhdCI6MTYwOTgzOTk0Nn0.vZvpb48YXMrNOcyzqYScayIg3Qg2WQW3_pnpu4m9zmY

{
    "teamId": "5ff1f36398be2200175b7517",
    "requestId": "5ff34e573cf4b500170bf1b6"
}


###