GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "firstname": "a",
    "lastname": "a",
    "email": "a@a.se",
    "password": "123456"
}