GET http://localhost:5000/api/users/userTeams/5ff7107a53041500170bf88e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZjcxMDdhNTMwNDE1MDAxNzBiZjg4ZSIsImZpcnN0bmFtZSI6IkZyZWRyaWsiLCJsYXN0bmFtZSI6IlRoZWxpbiIsImVtYWlsIjoiZkB0LnNlIiwidGVhbSI6WyI1ZmY3MTA4ODUzMDQxNTAwMTcwYmY4OGYiLCI1ZmY3MTMzOTJkM2NmYTBkYTQ0YjA0ZDAiXSwiYWN0aXZlVGVhbSI6IjVmZjcxMDg4NTMwNDE1MDAxNzBiZjg4ZiIsImlhdCI6MTYxMDEwMzc4M30.BG_UAOUcET2TktsSKu3MSdCTPlGVumUBU5dfb_-vYrY

###

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "lastname": "ad",
    "email": "ad@a.se",
    "password": "1234"
}